### ISSUE TITLE
Huawei Fingerprint Gestures

### ISSUE THREAD

**Issue by HugoOliTorres** [Descendant/rom_status#5]
**Describe the bug**
The Fingerprint gestures don't work properly. Fingerprint button is not mapped to home, it does other stuff other then going home or back. It just presses stuff.

**To Reproduce**
Enable Huawei Fingerprint Gestures

**Expected behavior**
Clicking fingerprint button and going home.

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 9
 - Descendant Version: OneDotTwo
 - Treble support type: arm64 a only
 - Gapps: No

**Full bugreport/trimmed logcat**
No logs

**Comment by Dil3mm4** [comment]
I was already aware about this issue and it will be fixed in the upcoming release. 

Furthermore, as a temporary fix until OneDotThree, follow this steps:

1. Download this file https://github.com/phhusson/vendor_hardware_overlay/blob/master/Huawei/Fingerprint/fingerprint.kl
2. Move the downloaded file to /system/phh/huawei (via adb or TWRP)

**Comment by Dil3mm4** [comment]
Fixed in latest release
